"""empty message

Revision ID: 7cb4d2b169e6
Revises: 9e632e514f33
Create Date: 2022-11-27 15:51:57.124916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb4d2b169e6'
down_revision = '9e632e514f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('booked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_slots', 'booked')
    # ### end Alembic commands ###
